# Test your FastAPI endpoints

GET http://127.0.0.1:8000/query?keywords=computer+vision
Content-Type: application/json

###

GET https://mirai.remisiki.com/trace/api

###

GET https://mirai.remisiki.com/trace/api/query?keywords=computer+vision

###

GET http://127.0.0.1:8000/complete?keywords=computer+vision
