# Test your FastAPI endpoints

###
# Test for normal query

GET http://127.0.0.1:8000/api/query?keywords=computer+vision

###
# Test for query with only one article result

GET http://127.0.0.1:8000/api/query?keywords=meshlrm

###
# Test for query with no results

GET http://127.0.0.1:8000/api/query?keywords=thisisabadquery

###
#Test for autocomplete

GET http://127.0.0.1:8000/api/complete?keywords=computer+vision
